services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws-devops-mcp
    volumes:
      - .:/app
      - ~/.aws:/home/app/.aws
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-data:
    driver: local
